apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: dc-metro-map
  namespace: release-managed-tpvi
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/dcmetromap@sha256:6af4d0a138a283d77a91be8a57793ac7571a066a741d3e5c2a0f2a03467fc8be
        name: container-image
        resources: {}
status: {}
